# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

gradle-curseforge-publish.interop.fabric-loom=false
gradle-curseforge-publish.interop.neoforged=false
gradle-curseforge-publish.interop.neogradle=false

# ==== Main Mod properties ====
maven_group = net.oxcodsnet.roadarchitect
archives_name = roadarchitect
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
junit_version=5.10.2


# ==== COMMON MOD META ====
mod_id=roadarchitect
mod_name=RoadArchitect
mod_description=Travel around the world without barriers: RoadArchitect automatically scans your world, finds villages, and other structures, and then lays a network of roads between them.
mod_authors=0xCoDSnet
mod_homepage=https://github.com/0xCoDSnet
mod_sources=https://github.com/0xCoDSnet/RoadArchitect
mod_license=Apache-2.0
mod_version = 1.6.0-alpha

# ==== For ALL ====
cloth_config_version=15.0.140

# ==== For Fabric ====
modmenu_version=11.0.3
fabric_loader_version = 0.16.14
#-
yarn_mappings = 1.21.1+build.1
fabric_api_version = 0.116.5+1.21.1

# ==== For NeoForge ====
neoforge_version = 21.1.187
yarn_mappings_patch_neoforge_version = 1.21+build.4
